spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/wishfaah
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

gemini.api.key= AQ.Ab8RN6KxQQA2nRGvlfEHml6VcggVgSRg8tTIxZzen9hWqdKxvQ

meta.catalog.id=966029846449135
meta.catalog.token=EAAcmzaWhyeoBRjpIfKZAoQZCYxsWRJGwnj1R4EFmp4DB8OxshALJAhrxgYx3WO9zACB1ZBzOO6ZAqiUDhkkolQhzkOUZCrHDBERVLlwchuAGBtCmsSiL2djJv2z6PGDWZCADBZBxWpO9OJ7739eDqIOZCpgdqiyXUWouzZBw1r0ZCx9rknZCHsVG9r6Js9HzyUJbUgotAZDZD